services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    working_dir: /app/backend
    image: backend
    ports:
      - "3500:3500"
    
 

  frontend:
    build:
     context: .
     dockerfile: Dockerfile.frontend
    working_dir: /app/frontend
    image: frontend
    ports:
      - "5173:5173"
    
   