FROM node:20

# Set the working directory for the frontend
WORKDIR /app/frontend

# Copy package.json and package-lock.json from the frontend directory
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy all frontend files
COPY frontend/ ./

# Expose the frontend port
EXPOSE 5173

# Start the frontend application
CMD ["npm", "run", "dev", "--", "--host"]
